---
- name: This will harden RHOSP services per the Red Hat OSP hardening guide
  hosts: all
  become: yes



  tasks:

     - name: Install buildah to get files from the containers
       yum:
          name: buildah
          state: present

     - name: Get running containers to for neutron
       command: "docker ps -q -f \"name=neutron*\""
       register: neutron_containers

     - name: Get current config from running container to disable validation of self-signed certificates
       command: "buildah copy \"{{ item }}\":/etc/nova/api-paste.ini /var/lib/config-data/puppet-generated/nova/etc/"
       with_items: "{{ neutron_containers.stdout_lines }}"

     - name: To disable validation of self-signed certificates
       lineinfile:
         path: /etc/nova/api-paste.ini
         line: "insecure=False"
         insertafter: "[filter:authtoken]"
