---
- name: This will harden RHOSP services per the Red Hat OSP hardening guide
  hosts: all
  become: yes



  tasks:
     - name: To disable validation of self-signed certificates
       lineinfile:
         path: /etc/nova/api-paste.ini
         line: "insecure=False"
         insertafter: "[filter:authtoken]"
