---
- name: This will harden RHOSP services per the Red Hat OSP hardening guide
  hosts: all
  become: yes



  tasks:
     - name: Get running container ID
       command: "docker ps -q"
       register: running_containers

     - name: Get current config from running container to disable validation of self-signed certificates
       #command: "docker cp \"{{ item }}\":/etc/nova/api-paste.ini /var/lib/config-data/puppet-generated/nova/etc/nova/"
       command: "docker cp nova_conductor:/etc/nova/api-paste.ini /var/lib/config-data/puppet-generated/nova/etc/nova/"
       ignore_errors: true

     - name: To disable validation of self-signed certificates for host
       lineinfile:
         path: /etc/nova/api-paste.ini
         line: "insecure=False"
         insertafter: "[filter:authtoken]"

     - name: To disable validation of self-signed certificates for containers
       lineinfile:
         path: /var/lib/config-data/puppet-generated/nova/etc/nova/api-paste.ini
         line: "insecure=False"
         insertafter: "[filter:authtoken]"

     - name: creating the httpd folder to be used in the next step
       file:
         path: /var/lib/config-data/puppet-generated/httpd/etc/conf/httpd/
         state: directory
         mode: 0755

     - name: Get /etc/httpd/conf/httpd.conf from running container to enable of HSTS
       command: "docker cp \"{{ item }}\":/etc/httpd/conf/httpd.conf /var/lib/config-data/puppet-generated/httpd/etc/httpd/conf/"
       with_items: "{{ running_containers.stdout_lines }}"
       ignore_errors: true

     - name: Enable HSTS for host
       lineinfile:
         path: /etc/httpd/conf/httpd.conf
         line: "LoadModule headers_module modules/mod_headers.so"

     - name: Enable HSTS for containers
       lineinfile:
         path: /var/lib/config-data/puppet-generated/httpd/etc/conf/httpd/httpd.conf
         line: "LoadModule headers_module modules/mod_headers.so"
       ignore_errors: true

     - name: creating the httpd folder to be used in the next step
       file:
         path: /var/lib/config-data/puppet-generated/httpd/etc/httpd/conf.d/
         state: directory
         mode: 0755

     - name: Get /etc/httpd/conf.d/ssl.conf from running container to enable of HSTS
       command: "docker cp \"{{ item }}\":/etc/httpd/conf.d/ssl.conf /var/lib/config-data/puppet-generated/httpd/etc/httpd/conf.d/"
       with_items: "{{ running_containers.stdout_lines }}"
       ignore_errors: true

     - name: Enable HSTS for host PT2
       lineinfile:
         path: /etc/httpd/conf.d/ssl.conf
         line: "Header always set Strict-Transport-Security \"max-age=63072000; includeSubDomains\""
         insertafter: "<VirtualHost _default_:443>"
      ignore_errors: true

     - name: Enable HSTS for containers PT2
       lineinfile:
         path: /var/lib/config-data/puppet-generated/httpd/etc/httpd/conf.d/httpd.conf
         line: "Header always set Strict-Transport-Security \"max-age=63072000; includeSubDomains\""
         insertafter: "<VirtualHost _default_:443>"
       ignore_errors: true
